// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Querriying;

namespace Querriying.Migrations
{
    [DbContext(typeof(ETicaretContext))]
    [Migration("20221117100313_mig1")]
    partial class mig1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Querriying.Parca", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ParcaAdi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UrunId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UrunId");

                    b.ToTable("Parcalar");
                });

            modelBuilder.Entity("Querriying.Urun", b =>
                {
                    b.Property<int>("UrunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Fiyat")
                        .HasColumnType("real");

                    b.Property<string>("UrunAdi")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UrunId");

                    b.ToTable("Urunler");
                });

            modelBuilder.Entity("Querriying.UrunParca", b =>
                {
                    b.Property<int>("UrunId")
                        .HasColumnType("int");

                    b.Property<int>("ParcaId")
                        .HasColumnType("int");

                    b.HasKey("UrunId", "ParcaId");

                    b.HasIndex("ParcaId");

                    b.ToTable("UrunParcalar");
                });

            modelBuilder.Entity("Querriying.Parca", b =>
                {
                    b.HasOne("Querriying.Urun", null)
                        .WithMany("Parcalar")
                        .HasForeignKey("UrunId");
                });

            modelBuilder.Entity("Querriying.UrunParca", b =>
                {
                    b.HasOne("Querriying.Parca", "Parca")
                        .WithMany()
                        .HasForeignKey("ParcaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Querriying.Urun", "Urun")
                        .WithMany()
                        .HasForeignKey("UrunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parca");

                    b.Navigation("Urun");
                });

            modelBuilder.Entity("Querriying.Urun", b =>
                {
                    b.Navigation("Parcalar");
                });
#pragma warning restore 612, 618
        }
    }
}
